language: python
python:
  - "2.7"

before_install:
- sh ./get_mpich.sh

install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/MLMCPy
  - python setup.py install

script:
  - pytest tests
  - ./mpich/bin/mpirun -np 2 pytest tests
  - ./mpich/bin/mpirun -np 3 pytest tests
